# Site settings
title: KARAT.
# description: Brussels based shop
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KARAT. 
# user_description: Yeah 
user_title: Sneaker & Fashion store • Restorations & cleaning • Exclusive releases & vintage streetwear •
email: none@none.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
instagram_username:  karatbrussels
facebook_username: karatbrussels


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'node_modules']
